abbr --add ga "git add"
abbr --add gb "git branch"
abbr --add gba "git branch -a"
abbr --add gbd "git branch -d"
abbr --add gbD "git branch -D"
abbr --add gbl "git blame"
abbr --add gca "git commit --amend"
abbr --add gcm --set-cursor "git commit -m \"%\""
abbr --add gco "git checkout"
abbr --add gcob "git checkout -b"
abbr --add gcp "git cherry-pick"
abbr --add gd "git diff"
abbr --add gds "git diff --staged"
abbr --add gm "git merge"
abbr --add gp "git pull"
abbr --add gpu "git push"
abbr --add grh "git reset HEAD"
abbr --add grs "git restore --staged"
abbr --add gs "git status"
abbr --add gsh "git show"
abbr --add gst "git stash"
abbr --add gstl "git stash list"
abbr --add gstp --set-cursor "git stash push -m \"%\""
abbr --add gstpop "git stash pop"
abbr --add gsw "git switch"

# Too much clutter for an abbreviation, make it an alias
alias gl="git log --graph --pretty=tformat:\"%C(yellow)%h%C(reset)%x09 %C(cyan)%aD%C(reset) %C(blue)%xE2%x89%x88 %ar%C(reset) %C(auto)%d%C(reset)%n %x09%x09 %s%n %x09%x09 %C(dim)%aN <%aE>%C(reset)%n\""
