status is-interactive; or return

abbr -a ga "git add"
abbr -a gb "git branch"
abbr -a gba "git branch -a"
abbr -a gbd "git branch -d"
abbr -a gbD "git branch -D"
abbr -a gbl "git blame"
abbr -a gca "git commit --amend"
abbr -a gcm --set-cursor "git commit -m \"%\""
abbr -a gco "git checkout"
abbr -a gcob "git checkout -b"
abbr -a gcp "git cherry-pick"
abbr -a gd "git diff"
abbr -a gds "git diff --stat"
abbr -a gl "git lg"
abbr -a gm "git merge"
abbr -a gp "git pull"
abbr -a gpu "git push"
abbr -a grh "git reset HEAD"
abbr -a grs "git restore --staged"
abbr -a gs "git status"
abbr -a gsh "git show"
abbr -a gst "git stash"
abbr -a gstl "git stash list"
abbr -a gstp --set-cursor "git stash push -m \"%\""
abbr -a gstpop "git stash pop"
abbr -a gsw "git switch"
