complete -c sqlite3 -n __completion_bypasses_wrapper -o AARGS -d 'Run  . archive ARGS and exit'
complete -c sqlite3 -n __completion_bypasses_wrapper -o append -d 'Append the database to the end of the file'
complete -c sqlite3 -n __completion_bypasses_wrapper -o ascii -d 'Set output mode to \'ascii\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o bail -d 'Stop after hitting an error'
complete -c sqlite3 -n __completion_bypasses_wrapper -o batch -d 'Force batch I/O'
complete -c sqlite3 -n __completion_bypasses_wrapper -o box -d 'Set output mode to \'box\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o column -d 'Query results will be displayed in a table like form, using whitespace charac…'
complete -c sqlite3 -n __completion_bypasses_wrapper -o cmd -d 'run  command before reading stdin'
complete -c sqlite3 -n __completion_bypasses_wrapper -o csv -d 'Set output mode to CSV (comma separated values)'
complete -c sqlite3 -n __completion_bypasses_wrapper -o deserialize -d 'Open the database using sqlite3_deserialize()'
complete -c sqlite3 -n __completion_bypasses_wrapper -o echo -d 'Print commands before execution'
complete -c sqlite3 -n __completion_bypasses_wrapper -o init -d 'Read and execute commands from  file , which can contain a mix of SQL stateme…'
complete -c sqlite3 -n __completion_bypasses_wrapper -o header -d 'Turn headers on or off'
complete -c sqlite3 -n __completion_bypasses_wrapper -o help -d 'Show help on options and exit'
complete -c sqlite3 -n __completion_bypasses_wrapper -o hexkeykey -d 'Open database with hexadecimal encryption key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o html -d 'Query results will be output as simple HTML tables'
complete -c sqlite3 -n __completion_bypasses_wrapper -o interactive -d 'Force interactive I/O'
complete -c sqlite3 -n __completion_bypasses_wrapper -o keykey -d 'Open database with raw encryption key  key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o json -d 'Set output mode to \'json\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o line -d 'Query results will be displayed with one value per line, rows separated by a …'
complete -c sqlite3 -n __completion_bypasses_wrapper -o list -d 'Query results will be displayed with the separator (|, by default) character …'
complete -c sqlite3 -n __completion_bypasses_wrapper -o lookaside -d 'Use  n entries of  size bytes for lookaside memory'
complete -c sqlite3 -n __completion_bypasses_wrapper -o markdown -d 'Set output mode to \'markdown\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o maxsizeN -d 'Limits size of a -deserialize database to  N bytes'
complete -c sqlite3 -n __completion_bypasses_wrapper -o memtrace -d 'Trace all memory allocations'
complete -c sqlite3 -n __completion_bypasses_wrapper -o newline -d 'Set output row separator.  Default is \'\\\\n\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o nofollow -d 'Refuse to open paths containing symbolic links'
complete -c sqlite3 -n __completion_bypasses_wrapper -o noncestring -d 'Set the safe-mode escape nonce to  string'
complete -c sqlite3 -n __completion_bypasses_wrapper -o nullvalue -d 'Set string used to represent NULL values.   Default is \'\' (empty string)'
complete -c sqlite3 -n __completion_bypasses_wrapper -o quote -d 'Set output mode to quote'
complete -c sqlite3 -n __completion_bypasses_wrapper -o readonly -d 'Open the database read-only'
complete -c sqlite3 -n __completion_bypasses_wrapper -o safe -d 'Enable safe-mode'
complete -c sqlite3 -n __completion_bypasses_wrapper -o separator -d 'Set output field separator.   Default is \'|\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o stats -d 'Print memory stats before each finalize'
complete -c sqlite3 -n __completion_bypasses_wrapper -o textkeyPASSPHRASE -d 'Text to be hashed into the encryption key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o table -d 'Set output mode to \'table\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o tabs -d 'Set output mode to \'tabs\''
complete -c sqlite3 -n __completion_bypasses_wrapper -o version -d 'Show SQLite version'
complete -c sqlite3 -n __completion_bypasses_wrapper -o vfs -d 'Use  name as the default VFS'
complete -c sqlite3 -n __completion_bypasses_wrapper -s A -d 'Run . archive ARGS and exit'
complete -c sqlite3 -n __completion_bypasses_wrapper -o hexkey -d 'Open database with hexadecimal encryption key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o key -d 'Open database with raw encryption key key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o maxsize -d 'Limits size of a -deserialize database to N bytes'
complete -c sqlite3 -n __completion_bypasses_wrapper -o nonce -d 'Set the safe-mode escape nonce to string'
complete -c sqlite3 -n __completion_bypasses_wrapper -o textkey -d 'Text to be hashed into the encryption key'
complete -c sqlite3 -n __completion_bypasses_wrapper -o zip -d 'Open the file as a zip archive'
