server:
    username: "sander"

    use-syslog: yes

    log-tag-queryreply: yes

    local-zone: "test." redirect
    local-data: "test. IN A 127.0.0.1"

    tls-cert-bundle: "/opt/homebrew/opt/ca-certificates/share/ca-certificates/cacert.pem"

remote-control:
    control-enable: yes

include-toplevel: "/opt/homebrew/etc/unbound/unbound.local.conf"
